// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// sd_init_log
void sd_init_log();
RcppExport SEXP _sdR_sd_init_log() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    sd_init_log();
    return R_NilValue;
END_RCPP
}
// sd_create_context
SEXP sd_create_context(Rcpp::List params);
RcppExport SEXP _sdR_sd_create_context(SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(sd_create_context(params));
    return rcpp_result_gen;
END_RCPP
}
// sd_destroy_context
void sd_destroy_context(SEXP ctx_sexp);
RcppExport SEXP _sdR_sd_destroy_context(SEXP ctx_sexpSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ctx_sexp(ctx_sexpSEXP);
    sd_destroy_context(ctx_sexp);
    return R_NilValue;
END_RCPP
}
// sd_generate_image
Rcpp::List sd_generate_image(SEXP ctx_sexp, Rcpp::List params);
RcppExport SEXP _sdR_sd_generate_image(SEXP ctx_sexpSEXP, SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ctx_sexp(ctx_sexpSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(sd_generate_image(ctx_sexp, params));
    return rcpp_result_gen;
END_RCPP
}
// sd_system_info_cpp
std::string sd_system_info_cpp();
RcppExport SEXP _sdR_sd_system_info_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(sd_system_info_cpp());
    return rcpp_result_gen;
END_RCPP
}
// sd_version_cpp
std::string sd_version_cpp();
RcppExport SEXP _sdR_sd_version_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(sd_version_cpp());
    return rcpp_result_gen;
END_RCPP
}
// sd_num_physical_cores_cpp
int sd_num_physical_cores_cpp();
RcppExport SEXP _sdR_sd_num_physical_cores_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(sd_num_physical_cores_cpp());
    return rcpp_result_gen;
END_RCPP
}
// sd_type_name_cpp
std::string sd_type_name_cpp(int type);
RcppExport SEXP _sdR_sd_type_name_cpp(SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(sd_type_name_cpp(type));
    return rcpp_result_gen;
END_RCPP
}
// sd_sample_method_name_cpp
std::string sd_sample_method_name_cpp(int method);
RcppExport SEXP _sdR_sd_sample_method_name_cpp(SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(sd_sample_method_name_cpp(method));
    return rcpp_result_gen;
END_RCPP
}
// sd_scheduler_name_cpp
std::string sd_scheduler_name_cpp(int sched);
RcppExport SEXP _sdR_sd_scheduler_name_cpp(SEXP schedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type sched(schedSEXP);
    rcpp_result_gen = Rcpp::wrap(sd_scheduler_name_cpp(sched));
    return rcpp_result_gen;
END_RCPP
}
// sd_create_upscaler
SEXP sd_create_upscaler(std::string esrgan_path, int n_threads, bool offload_params_to_cpu, bool direct, int tile_size);
RcppExport SEXP _sdR_sd_create_upscaler(SEXP esrgan_pathSEXP, SEXP n_threadsSEXP, SEXP offload_params_to_cpuSEXP, SEXP directSEXP, SEXP tile_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type esrgan_path(esrgan_pathSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< bool >::type offload_params_to_cpu(offload_params_to_cpuSEXP);
    Rcpp::traits::input_parameter< bool >::type direct(directSEXP);
    Rcpp::traits::input_parameter< int >::type tile_size(tile_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(sd_create_upscaler(esrgan_path, n_threads, offload_params_to_cpu, direct, tile_size));
    return rcpp_result_gen;
END_RCPP
}
// sd_upscale
Rcpp::List sd_upscale(SEXP upscaler_sexp, Rcpp::List image, int upscale_factor);
RcppExport SEXP _sdR_sd_upscale(SEXP upscaler_sexpSEXP, SEXP imageSEXP, SEXP upscale_factorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type upscaler_sexp(upscaler_sexpSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type image(imageSEXP);
    Rcpp::traits::input_parameter< int >::type upscale_factor(upscale_factorSEXP);
    rcpp_result_gen = Rcpp::wrap(sd_upscale(upscaler_sexp, image, upscale_factor));
    return rcpp_result_gen;
END_RCPP
}
// sd_convert_model
bool sd_convert_model(std::string input_path, std::string output_path, int output_type, std::string vae_path, std::string tensor_type_rules, bool convert_name);
RcppExport SEXP _sdR_sd_convert_model(SEXP input_pathSEXP, SEXP output_pathSEXP, SEXP output_typeSEXP, SEXP vae_pathSEXP, SEXP tensor_type_rulesSEXP, SEXP convert_nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type input_path(input_pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type output_path(output_pathSEXP);
    Rcpp::traits::input_parameter< int >::type output_type(output_typeSEXP);
    Rcpp::traits::input_parameter< std::string >::type vae_path(vae_pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type tensor_type_rules(tensor_type_rulesSEXP);
    Rcpp::traits::input_parameter< bool >::type convert_name(convert_nameSEXP);
    rcpp_result_gen = Rcpp::wrap(sd_convert_model(input_path, output_path, output_type, vae_path, tensor_type_rules, convert_name));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_sdR_sd_init_log", (DL_FUNC) &_sdR_sd_init_log, 0},
    {"_sdR_sd_create_context", (DL_FUNC) &_sdR_sd_create_context, 1},
    {"_sdR_sd_destroy_context", (DL_FUNC) &_sdR_sd_destroy_context, 1},
    {"_sdR_sd_generate_image", (DL_FUNC) &_sdR_sd_generate_image, 2},
    {"_sdR_sd_system_info_cpp", (DL_FUNC) &_sdR_sd_system_info_cpp, 0},
    {"_sdR_sd_version_cpp", (DL_FUNC) &_sdR_sd_version_cpp, 0},
    {"_sdR_sd_num_physical_cores_cpp", (DL_FUNC) &_sdR_sd_num_physical_cores_cpp, 0},
    {"_sdR_sd_type_name_cpp", (DL_FUNC) &_sdR_sd_type_name_cpp, 1},
    {"_sdR_sd_sample_method_name_cpp", (DL_FUNC) &_sdR_sd_sample_method_name_cpp, 1},
    {"_sdR_sd_scheduler_name_cpp", (DL_FUNC) &_sdR_sd_scheduler_name_cpp, 1},
    {"_sdR_sd_create_upscaler", (DL_FUNC) &_sdR_sd_create_upscaler, 5},
    {"_sdR_sd_upscale", (DL_FUNC) &_sdR_sd_upscale, 3},
    {"_sdR_sd_convert_model", (DL_FUNC) &_sdR_sd_convert_model, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_sdR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
